[Interface]
PrivateKey = EM8InN6Ck0SQV7Wfs4z1WLMrsK/naOWZkdy4nXi/ykw=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = 8RpSFdIWxat/AEw/qN1R0wAtvKYdTutvawV5VveN4C4=
PresharedKey = qF/w0Zl8Zwm5B97klMZfeSxezk111s1ZIb6dTzmIsUE=
Endpoint = 140.82.35.109:51013
AllowedIPs = 0.0.0.0/0,::/0
